(function(){var a={config:{},Observer:{},module:function(b,c){a[b]=new c(this)},addObserver:function(a,c){this.Observer[a]=this.Observer[a]||[];this.Observer[a].push(c)},fireEvent:function(a,c){for(var d=this.Observer[a],e=0;e<d.length;e++)d[e].eventListener[a](c)},init:function(){this.status.clipNodes=[];this.readConfig();this.view.init();this.eventBind.init()},setConfig:function(){},readConfig:function(){this.config.left=parseInt(this.model.read("dorsy_left"))||0;this.config.top=parseInt(this.model.read("dorsy_top"))||
0},status:{}};window.dorsyClip={module:function(b,c){a.module(b,c)},init:function(){a.init()},set:function(b){a.config.designUrl=b}};window.$DC||(window.$DC=window.dorsyClip)})();
window.onload=function(){if("undefined"==typeof window.localStorage){var a=window.localStorage={},b=document,c=b.body,d=b.documentElement,e=function(a,b,c,e){d.load("data-userdata");c=d.getAttribute("data-userdata");e=RegExp("\\b"+a+"\\b,?","i");hasKey=e.test(c)?1:0;c=b?c.replace(e,"").replace(",",""):hasKey?c:""===c?a:c.split(",").concat(a).join(",");d.setAttribute("data-userdata",c);d.save("data-userdata")};c.addBehavior("#default#userData");d.addBehavior("#default#userData");a.getItem=function(a){c.load(a);
return c.getAttribute(a)};a.setItem=function(a,b){c.setAttribute(a,b);c.save(a);e(a)};a.removeItem=function(a){c.removeAttribute(a);c.save(a);e(a,1)};a.clear=function(){d.load("data-userdata");for(var a=d.getAttribute("data-userdata").split(","),b=a.length,e=0;e<b;e++)c.removeAttribute(a[e]),c.save(a[e]);d.setAttribute("data-userdata","");d.save("data-userdata")}}dorsyClip.init()};
dorsyClip.module("eventBind",function(a){var b;b=window.addEventListener?function(a,b,e){a.addEventListener(b,e,!1)}:function(a,b,e){a.attachEvent("on"+b,e)};return{init:function(){var c=0,d,e,h,f,l;b(window,"mousedown",function(b){a.status.isOpen&&!/dorsyIcon/.test(b.target.className)&&(c=1,d=b.clientX,e=b.clientY,h=parseInt(a.el.style.left),f=parseInt(a.el.style.top),a.status.isClipT&&(l=a.view.createClipEle(d,e),b.preventDefault()))});b(window,"mouseup",function(){c=0;a.status.slideDown=0});b(document.body,
"mousemove",function(b){if(a.status.isOpen&&c){var j=b.clientX-d,g=b.clientY-e;a.status.isClipT&&(l.rect.style.width=j+"px",l.rect.style.height=g+"px",a.view.updateClipT(l,j,g));a.status.slideDown?0<k+j&&k+j<parseInt(a.util.css(document.getElementById("dorsySlideBar"),"width"))&&(document.getElementById("dorsySlideA").style.left=k+j+"px",j=(k+j)/parseInt(a.util.css(document.getElementById("dorsySlideBar"),"width")),a.util.Bar.notify(j),b.preventDefault()):(c&&(!a.status.isFixed&&!a.status.isClipT)&&
(a.el.style.left=h+j+"px",a.el.style.top=f+g+"px"),b.preventDefault())}});var g=0;b(window,"keydown",function(b){if(a.status.isOpen&&a.el){17==b.keyCode&&(g=1);var c=parseInt(a.el.style.left),d=parseInt(a.el.style.top);39==b.keyCode&&g&&(a.el.style.left=c+1+"px",b.preventDefault());37==b.keyCode&&g&&(a.el.style.left=c-1+"px",b.preventDefault());38==b.keyCode&&g&&(a.el.style.top=d-1+"px",b.preventDefault());40==b.keyCode&&g&&(a.el.style.top=d+1+"px",b.preventDefault())}});b(window,"keyup",function(a){17==
a.keyCode&&(g=0)});b(document.getElementById("dorsyFix"),"click",function(){a.status.isOpen&&(a.status.isFixed=a.status.isFixed?0:1,a.view.toggleFixDesign())});b(document.getElementById("dorsyClipT"),"click",function(){a.status.isOpen&&(a.status.isClipT=a.status.isClipT?0:1,a.view.toggleClipT())});b(document.getElementById("dorsyLogo"),"click",function(){a.status.isOpen=a.status.isOpen?0:1;a.view.toggleOpen(this)});b(document.getElementById("dorsyOpacity"),"click",function(){a.status.isOpacity=a.status.isOpacity?
0:1;a.view.toggleOpacity()});var k=0;a.util.addEvent(document.body,"#dorsySlideA","mousedown",function(){a.status.slideDown=1;k=parseInt(a.util.css(this,"left"))})}}});dorsyClip.module("model",function(){return{write:function(a,b){localStorage.setItem(a,b)},read:function(a){return localStorage.getItem(a)}}});
dorsyClip.module("util",function(){return{addEvent:function(a,b,c,d){var e="",h=0;if("string"==typeof b)switch(h=1,!0){case /^\./.test(b):e="className";b=b.replace(".","");b=RegExp(" *"+b+" *");break;case /^\#/.test(b):e="id";b=RegExp(b.replace("#",""));break;default:b=RegExp(b),e="tagName"}var f=window.addEventListener?"addEventListener":"attachEvent";c=window.addEventListener?c:"on"+c;a[f](c,function(c){function g(f){if(h){if(b.test(f[e])){d.call(f,c);return}}else if(b==f){d.call(f,c);return}f==
a||f.parentNode==a||g(f.parentNode)}g(c.srcElement)})},each:function(a,b){for(var c=0,d=a.length;c<d;c++)b.call(a[c],c)},addClass:function(a,b){a.className.match(b)||(a.className+=" "+b)},removeClass:function(a,b){a.className=a.className.replace(RegExp(" ?"+b),"")},firstChild:function(a){for(var b=0;b<a.childNodes.length;b++)if(1==a.childNodes[b].nodeType)return a.childNodes[b]},lastChild:function(a){for(var b=a.childNodes.length-1;0<=b;b--)if(1==a.childNodes[b].nodeType)return a.childNodes[b]},animate:function(a,
b,c,d){var e={},h={},f;for(f in b){var l=parseInt(this.css(a,f));h[f]=l;e[f]=parseInt(parseInt(b[f])-l)/c}var g=0,k;k=setInterval(function(){g++;var b=1E3*(g/60)/c,b=(0*Math.pow(1-b,3)+1.26*b*Math.pow(1-b,2)+3*b*b*(1-b)+1*Math.pow(b,3))*c,f;for(f in e)a.style[f]=h[f]+e[f]*b+"px";g==60*(c/1E3)&&(clearInterval(k),d&&d())},1E3/60)},cookie:function(a,b){if(!b)return RegExp(";?"+a+"=([^;]+);").exec(document.cookie)[1]||null},loadScript:function(a){var b=document.createElement("script");b.src=a;b.onload=
function(){};document.body.appendChild(b)},css:function(a,b){try{return a.currentStyle[b]}catch(c){return getComputedStyle(a).getPropertyValue(b)}},Bar:{observer:[],notify:function(a){for(var b=0;b<this.observer.length;b++)this.observer[b](a)},addObserver:function(a){this.observer.push(a)}}}});
dorsyClip.module("view",function(a){return{eventListener:{getBottleSuccess:function(){}},init:function(){this.createDesignEle();this.createToolBar();a.status.isOpen=1},createDesignEle:function(){document.body.style.position="relative";var b=document.createElement("img");b.src=a.config.designUrl||"home.jpg";b.style.position="absolute";b.style.left=a.config.left+"px";b.style.top=a.config.top+"px";b.style.opacity="0.5";b.style.zIndex="999";b.setAttribute("draggable","false");b.onerror=function(){if(a.config.designUrl)throw Error("\u89c6\u89c9\u56fe\u7247"+
b.src+"\u6ca1\u6709\u627e\u5230,\u8bf7\u68c0\u67e5\u8def\u5f84\u662f\u5426\u6b63\u786e--dorsyClip");if(/home.png/.test(b.src))throw Error("\u89c6\u89c9\u56fe\u7247"+b.src+"\u6ca1\u6709\u627e\u5230,\u8bf7\u68c0\u67e5\u8def\u5f84\u662f\u5426\u6b63\u786e--dorsyClip");b.src="home.png"};document.body.appendChild(b);a.el=b},createToolBar:function(){var a=document.createElement("div");a.className="dorsyToolbarWrapper";document.body.appendChild(a);a.innerHTML="<div class='dorsyToolbar'><div id='dorsyFix' class='dorsyIcon' title='\u56fa\u5b9a'></div><div id='dorsyClipT' title='\u6d4b\u8ddd' class='dorsyIcon'></div><div id='dorsyScale' title='\u7f29\u653e' class='dorsyIcon'></div><div class='dorsyIcon' id='dorsyOpacity' title='\u900f\u660e\u5ea6'></div><div id='dorsyLogo' style='width:131px' title='\u5f00\u5173'></div></div>"},
setBodyOpicy:function(a){for(var c=document.body.childNodes,d=0;d<c.length;d++)c[d]&&c[d].className&&!/^dorsy/.test(c[d].className)&&c[d].style&&(c[d].style.opacity=a)},createSlideBar:function(){var b=document.createElement("div");b.innerHTML="<div id='dorsySlideBar' class='dorsySlideBar' rangeMin='-50' rangeMax='50'><a id='dorsySlideA' draggable='false' href='#'></a><div class='dMsg'></div></div>";b.className="dorsySlideBarWrapper";a.slideEle=b;document.body.appendChild(b);a.util.animate(b,{bottom:"85px"},
300);var c=this;a.util.Bar.addObserver(function(b){a.status.opacityValue=b;a.status.isFixed&&c.setBodyOpicy(b);a.status.isFixed||(a.el.style.opacity=b)})},toggleOpacity:function(){a.status.isOpacity?(this.createSlideBar(),a.util.addClass(document.getElementById("dorsyOpacity"),"dorsyIconSelected")):(a.util.removeClass(document.getElementById("dorsyOpacity"),"dorsyIconSelected"),a.util.animate(a.slideEle,{bottom:"68px",opacity:"0"},300,function(){document.body.removeChild(a.slideEle)}))},fixDesign:function(){a.config.left=
parseInt(a.el.style.left);a.config.top=parseInt(a.el.style.top);console.log("t"+a.config.top);a.model.write("dorsy_left",a.config.left);a.model.write("dorsy_top",a.config.top);document.body.removeChild(a.el);a.el=null;this.setBodyOpicy(0.5);document.body.style.background="url("+a.config.designUrl+") no-repeat "+a.config.left+"px "+a.config.top+"px";a.util.addClass(document.getElementById("dorsyFix"),"dorsyIconSelected")},unfixDesign:function(){document.body.style.background="none";this.setBodyOpicy(1);
this.createDesignEle();a.util.removeClass(document.getElementById("dorsyFix"),"dorsyIconSelected")},toggleFixDesign:function(){a.status.isFixed?this.fixDesign():this.unfixDesign()},createClipEle:function(b,c){var d=b||0,e=c||0,h=document.createElement("div");h.className="dorsyRect";h.style.left=d+"px";h.style.top=e+"px";var f=document.createElement("div");f.className="dorsyInfo";f.style.left=d+"px";f.style.top=e+"px";document.body.appendChild(h);document.body.appendChild(f);d={rect:h,info:f};a.status.clipNodes.push(d);
return d},updateClipT:function(a,c,d){a.info.innerHTML="\u957f\u5ea6: <span class='dorsyInfoNum'>"+c+"</span>px, \u9ad8\u5ea6:<span class='dorsyInfoNum'>"+d+"</span>px"},toggleClipT:function(){a.status.isClipT?(a.util.addClass(document.getElementById("dorsyClipT"),"dorsyIconSelected"),document.body.style.cursor="crosshair"):(a.util.removeClass(document.getElementById("dorsyClipT"),"dorsyIconSelected"),document.body.style.cursor="auto",this.clearClipT())},clearClipT:function(){for(var b=a.status.clipNodes,
c=0,d=b.length;c<d;c++)document.body.removeChild(b[c].rect),document.body.removeChild(b[c].info);a.status.clipNodes=[]},toggleOpen:function(b){var c=this;a.status.isOpen?a.util.animate(b,{width:"131px"},600,function(){!a.status.isFixed&&c.unfixDesign();a.status.isFixed&&(document.body.style.background="url("+a.config.designUrl+") no-repeat "+a.config.left+"px "+a.config.top+"px",c.setBodyOpicy(0.5))}):a.util.animate(b,{width:"78px"},600,function(){!a.status.isFixed&&document.body.removeChild(a.el);
document.body.style.background="none";c.setBodyOpicy(1);a.status.isOpacity&&!(a.status.isOpacity=0)&&c.toggleOpacity()})}}});